apiVersion: v1
kind: Service
metadata:
  name: mvc-service
  namespace: skr-namespace
spec:
  selector:
    app: mvc-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer